"""Compile the LAWN LORD brand kit into docs/brand/.

Single source of truth for the brand: the palette (extracted from the logo),
the type pairing, and the radius — emitted as everything a Tailwind + shadcn/ui
project needs, plus a visual swatch sheet and a PDF brand guide.

    uv run python scripts/build_brand_kit.py

Outputs (docs/brand/):
  tokens.css          shadcn semantic tokens (:root light + .dark, HSL triplets) + brand scale
  tailwind.preset.js  Tailwind preset (semantic colors via hsl(var()), brand scale, fonts, radius)
  fonts.css           Google Fonts import (Cinzel display + Inter body)
  palette.svg         swatch sheet
  brand-guide.pdf     the guide (logo, color, type, tokens, usage)
"""

from __future__ import annotations

import colorsys
from pathlib import Path

import fitz

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "brand"
ASSETS = ROOT / "docs" / "assets"

# ── Brand palette (named; hexes curated from the logo extraction) ────────────
BRAND = [
    ("ink", "#0B0E06", "near-black base — page background"),
    ("charcoal", "#11160A", "cards / panels"),
    ("forest", "#1E3A12", "dark green — secondary"),
    ("lawn", "#2F5217", "the LAWN green"),
    ("grass", "#4A7A22", "bright grass — accent"),
    ("gold", "#CFA13F", "the LORD gold — primary"),
    ("gold-light", "#EFC666", "gold highlight"),
    ("gold-deep", "#BB8527", "gold shadow"),
    ("parchment", "#ECE3CC", "cream — foreground on dark"),
    ("stone", "#6B7280", "castle stone — neutral"),
]
HEX = {name: hexc for name, hexc, _ in BRAND}

# ── shadcn semantic tokens → brand color (dark is primary; light provided too)
DARK = {
    "background": "ink", "foreground": "parchment",
    "card": "charcoal", "card-foreground": "parchment",
    "popover": "charcoal", "popover-foreground": "parchment",
    "primary": "gold", "primary-foreground": "ink",
    "secondary": "forest", "secondary-foreground": "parchment",
    "muted": "charcoal", "muted-foreground": "stone",
    "accent": "lawn", "accent-foreground": "parchment",
    "destructive": "#B91C1C", "destructive-foreground": "#FFFFFF",
    "border": "#2A340B", "input": "#2A340B", "ring": "gold",
}
LIGHT = {
    "background": "#F6F1E3", "foreground": "#14260A",
    "card": "#FCF8EE", "card-foreground": "#14260A",
    "popover": "#FCF8EE", "popover-foreground": "#14260A",
    "primary": "gold-deep", "primary-foreground": "#FFF8E7",
    "secondary": "lawn", "secondary-foreground": "#FFFFFF",
    "muted": "parchment", "muted-foreground": "#5C6B49",
    "accent": "grass", "accent-foreground": "#FFFFFF",
    "destructive": "#B91C1C", "destructive-foreground": "#FFFFFF",
    "border": "#DCD2B6", "input": "#DCD2B6", "ring": "gold-deep",
}
RADIUS = "0.5rem"
FONT_DISPLAY = "Cinzel"   # regal serif — crowns & castles
FONT_SANS = "Inter"       # clean body
SEMANTIC_ORDER = list(DARK.keys())


def _rgb(hexc: str) -> tuple[float, float, float]:
    h = hexc.lstrip("#")
    return tuple(int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))


def _hsl_triplet(hexc: str) -> str:
    r, g, b = _rgb(hexc)
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    return f"{round(h * 360)} {round(s * 100)}% {round(l * 100)}%"


def _resolve(v: str) -> str:
    return HEX[v] if v in HEX else v


# ── tokens.css ───────────────────────────────────────────────────────────────
def write_tokens_css() -> None:
    def block(selector: str, mapping: dict) -> str:
        lines = [f"{selector} {{"]
        for tok in SEMANTIC_ORDER:
            lines.append(f"  --{tok}: {_hsl_triplet(_resolve(mapping[tok]))};")
        lines.append(f"  --radius: {RADIUS};")
        lines.append("}")
        return "\n".join(lines)

    brand_vars = "\n".join(f"  --brand-{n}: {h};" for n, h, _ in BRAND)
    css = f"""/* LAWN LORD design tokens — generated by scripts/build_brand_kit.py.
   shadcn/ui semantic tokens as HSL triplets (use as hsl(var(--token))), plus the
   raw brand scale. Light is the default; add class="dark" for the dark theme. */

:root {{
{block(":root", LIGHT).split("{", 1)[1].rsplit("}", 1)[0].rstrip()}
}}

.dark {{
{block(".dark", DARK).split("{", 1)[1].rsplit("}", 1)[0].rstrip()}
}}

/* raw brand scale (hex) */
:root {{
{brand_vars}
}}
"""
    (OUT / "tokens.css").write_text(css, encoding="utf-8")


# ── tailwind.preset.js ────────────────────────────────────────────────────────
def write_tailwind_preset() -> None:
    sem = ",\n".join(
        f'        "{t}": "hsl(var(--{t}))"' for t in SEMANTIC_ORDER
        if t not in ("primary", "secondary", "muted", "accent", "card", "popover")
    )
    pairs = ""
    for base in ("primary", "secondary", "muted", "accent", "card", "popover"):
        pairs += (
            f'        "{base}": {{ DEFAULT: "hsl(var(--{base}))", '
            f'foreground: "hsl(var(--{base}-foreground))" }},\n'
        )
    brand = ",\n".join(f'          "{n}": "{h}"' for n, h, _ in BRAND)
    js = f"""// LAWN LORD Tailwind preset — generated by scripts/build_brand_kit.py.
// Pairs with docs/brand/tokens.css (shadcn variables). Usage:
//   tailwind.config.js → module.exports = {{ presets: [require('./docs/brand/tailwind.preset.js')] }}
// Then: bg-background text-foreground bg-primary text-primary-foreground bg-brand-gold font-display
module.exports = {{
  darkMode: ["class"],
  theme: {{
    extend: {{
      colors: {{
{pairs}{sem},
        brand: {{
{brand}
        }},
      }},
      fontFamily: {{
        display: ['"{FONT_DISPLAY}"', "serif"],
        sans: ['"{FONT_SANS}"', "ui-sans-serif", "system-ui", "sans-serif"],
      }},
      borderRadius: {{
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      }},
    }},
  }},
}};
"""
    (OUT / "tailwind.preset.js").write_text(js, encoding="utf-8")


# ── fonts.css ─────────────────────────────────────────────────────────────────
def write_fonts_css() -> None:
    css = f"""/* LAWN LORD type — Google Fonts. Import once (e.g. in your globals.css). */
@import url("https://fonts.googleapis.com/css2?family={FONT_DISPLAY}:wght@500;600;700;800&family={FONT_SANS}:wght@400;500;600;700&display=swap");

:root {{
  --font-display: "{FONT_DISPLAY}", serif;   /* headings / wordmark — regal */
  --font-sans: "{FONT_SANS}", ui-sans-serif, system-ui, sans-serif; /* body / UI */
}}
"""
    (OUT / "fonts.css").write_text(css, encoding="utf-8")


# ── palette.svg ───────────────────────────────────────────────────────────────
def write_palette_svg() -> None:
    sw, gap, pad, top = 150, 16, 24, 70
    cols = len(BRAND)
    w = pad * 2 + cols * sw + (cols - 1) * gap
    h = top + sw + 64
    cells = []
    for i, (name, hexc, _role) in enumerate(BRAND):
        x = pad + i * (sw + gap)
        # contrast label color
        r, g, b = _rgb(hexc)
        lum = 0.299 * r + 0.587 * g + 0.114 * b
        ink = "#0B0E06" if lum > 0.55 else "#ECE3CC"
        cells.append(
            f'<rect x="{x}" y="{top}" width="{sw}" height="{sw}" rx="10" fill="{hexc}" '
            f'stroke="#00000022"/>'
            f'<text x="{x + 12}" y="{top + sw - 34}" fill="{ink}" font-family="Inter,sans-serif" '
            f'font-size="15" font-weight="700">{name}</text>'
            f'<text x="{x + 12}" y="{top + sw - 14}" fill="{ink}" font-family="monospace" '
            f'font-size="13">{hexc}</text>'
        )
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" '
        f'viewBox="0 0 {w} {h}">'
        f'<rect width="{w}" height="{h}" fill="#0B0E06"/>'
        f'<text x="{pad}" y="44" fill="#ECE3CC" font-family="Cinzel,serif" font-size="28" '
        f'font-weight="700">LAWN LORD — palette</text>'
        + "".join(cells)
        + "</svg>"
    )
    (OUT / "palette.svg").write_text(svg, encoding="utf-8")


# ── brand-guide.pdf ───────────────────────────────────────────────────────────
def write_pdf() -> None:
    doc = fitz.open()
    GOLD, INK, CREAM, GREEN = (0.81, 0.63, 0.25), (0.04, 0.05, 0.02), (0.93, 0.89, 0.80), (0.18, 0.32, 0.09)

    def fill_bg(page):
        page.draw_rect(page.rect, color=INK, fill=INK)

    # Cover
    p = doc.new_page(width=612, height=792)
    fill_bg(p)
    crest = ASSETS / "crest.png"
    if crest.exists():
        p.insert_image(fitz.Rect(206, 150, 406, 350), filename=str(crest))
    word = ASSETS / "lawnlord.png"
    if word.exists():
        p.insert_image(fitz.Rect(146, 380, 466, 570), filename=str(word), keep_proportion=True)
    p.insert_textbox(fitz.Rect(0, 610, 612, 650), "BRAND GUIDE", fontsize=24, color=GOLD,
                     fontname="tiro", align=fitz.TEXT_ALIGN_CENTER)
    p.insert_textbox(fitz.Rect(0, 650, 612, 690), "Defend your castle. Protect your kingdom.",
                     fontsize=12, color=CREAM, fontname="helv", align=fitz.TEXT_ALIGN_CENTER)

    # Colors
    p = doc.new_page(width=612, height=792)
    fill_bg(p)
    p.insert_text((48, 64), "Color", fontsize=26, color=GOLD, fontname="tiro")
    y = 92
    for name, hexc, role in BRAND:
        col = _rgb(hexc)
        p.draw_rect(fitz.Rect(48, y, 118, y + 48), color=(0.1, 0.1, 0.1), fill=col)
        p.insert_text((132, y + 18), f"{name}", fontsize=13, color=CREAM, fontname="hebo")
        p.insert_text((132, y + 36), f"{hexc}   —   {role}", fontsize=10, color=(0.7, 0.72, 0.66),
                      fontname="cour")
        y += 60

    # Type + tokens
    p = doc.new_page(width=612, height=792)
    fill_bg(p)
    p.insert_text((48, 64), "Type", fontsize=26, color=GOLD, fontname="tiro")
    p.insert_text((48, 104), f"Display — {FONT_DISPLAY}", fontsize=12, color=GREEN, fontname="hebo")
    p.insert_textbox(fitz.Rect(48, 112, 564, 150), "LAWN LORD", fontsize=30, color=CREAM,
                     fontname="tiro")
    p.insert_text((48, 176), f"Body — {FONT_SANS}", fontsize=12, color=GREEN, fontname="hebo")
    p.insert_textbox(fitz.Rect(48, 184, 564, 230),
                     "Ingest a case's filings and sort them into the schema you need to "
                     "analyze the case and fight it.", fontsize=12, color=CREAM, fontname="helv")
    p.insert_text((48, 268), "Tokens & usage", fontsize=26, color=GOLD, fontname="tiro")
    usage = (
        "docs/brand/tokens.css  — shadcn/ui semantic variables (light :root + .dark), HSL triplets.\n"
        "docs/brand/tailwind.preset.js — Tailwind preset: semantic colors via hsl(var()), the\n"
        "    brand-* scale, font families (display/sans), and radius.\n"
        "docs/brand/fonts.css   — Google Fonts import (Cinzel + Inter).\n\n"
        "shadcn:  copy tokens.css into your globals.css (or @import it).\n"
        "tailwind: presets: [require('./docs/brand/tailwind.preset.js')].\n"
        "classes:  bg-background text-foreground  bg-primary text-primary-foreground\n"
        "          bg-brand-gold text-brand-parchment  font-display  rounded-lg"
    )
    p.insert_textbox(fitz.Rect(48, 300, 564, 560), usage, fontsize=11, color=CREAM, fontname="cour")

    doc.save(str(OUT / "brand-guide.pdf"))
    doc.close()


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    write_tokens_css()
    write_tailwind_preset()
    write_fonts_css()
    write_palette_svg()
    write_pdf()
    print(f"brand kit → {OUT}")
    for f in sorted(OUT.iterdir()):
        print(f"  {f.name}  ({f.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
